name: automata_simulator
description: A tool designed to simulate Finite Automata.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
